export const CREATE_CONTACT = 'CREATE_CONTACT';
export const UPDATE_CONTACTS = 'UPDATE_CONTACTS';
export const REQUEST_CONTACTS_SUCCESS = 'REQUEST_CONTACTS_SUCCESS';
export const DELETE_CONTACT = 'DELETE_CONTACT';

export const SHOW_LOADER = 'SHOW_LOADER';
export const HIDE_LOADER = 'HIDE_LOADER';
